import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Susmita',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Anusha',
      email: 'user1@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
    {
      name: 'Saloni',
      email: 'user2@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Handmade sweater ',
      category: 'Sweaters',
      image: '/images/img1.jpg',
      price: 60,
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
      slug: 'sweater-1',
      description: 'high quality sweater',
    },
    {
      //_id: '2',
      name: 'Handmade sweater ',
      category: 'Sweaters',
      image: '/images/img2.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'sweater-2',
      description: 'high quality sweater',
    },
    {
      //_id: '3',
      name: 'Handmade sweater ',
      category: 'Sweaters',
      image: '/images/img3.jpg',
      price: 80,
      rating: 4.5,
      numReviews: 12,
      countInStock: 0,
      slug: 'sweater-3',
      description: 'high quality sweater',
    },
    {
      // _id: '4',
      name: 'Handmade sweater ',
      category: 'Sweaters',
      image: '/images/img4.jpg',
      price: 100,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'sweater-4',
      description: 'high quality sweater',
    },
    //dream catcher
    {
      //_id: '5',
      name: 'Dream catcher ',
      category: 'Dreamcatchers',
      image: '/images/img5.jpg',
      price: 40,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'dreamCatcher-1',
      description: 'handmade product',
    },
    {
      //_id: '6',
      name: 'Dream catcher',
      category: 'Dreamcatchers',
      image: '/images/img6.jpg',
      price: 30,
      rating: 4.5,
      numReviews: 15,
      countInStock: 0,
      slug: 'dreamCatcher-2',
      description: 'handmade product',
    },
    {
      // _id: '7',
      name: 'Dream catcher ',
      category: 'Dreamcatchers',
      image: '/images/img7.jpg',
      price: 40,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'dreamCatcher-3',
      description: 'handmade product',
    },
    {
      //_id: '8',
      name: 'Dream catcher',
      category: 'Dreamcatchers',
      image: '/images/img8.jpg',
      price: 80,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'dreamCatcher-4',
      description: 'handmade product',
    },
    //jewellery
    {
      // _id: '9',
      name: 'Rustic Handmade Jewellery',
      category: 'Jewelleries',
      image: '/images/img9.jpg',
      price: 40,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'jewellery-1',
      description: 'handmade product',
    },
    {
      //_id: '10',
      name: 'Rustic Handmade Jewellery',
      category: 'Jewelleries',
      image: '/images/img10.jpg',
      price: 50,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'jewellery-2',
      description: 'handmade product',
    },
    {
      // _id: '11',
      name: 'Rustic Handmade Jewellery',
      category: 'Jewelleries',
      image: '/images/img11.jpg',
      price: 30,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'jewellery-3',
      description: 'handmade product',
    },
    {
      // _id: '12',
      name: 'Rustic Handmade Jewellery',
      category: 'Jewelleries',
      image: '/images/img12.jpg',
      price: 60,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'jewellery-4',
      description: 'handmade product',
    },
    //baskets
    {
      // _id: '13',
      name: 'Basket',
      category: 'Baskets',
      image: '/images/img13.jpg',
      price: 90,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'basket-1',
      description: 'handmade product',
    },
    {
      //_id: '14',
      name: 'Basket',
      category: 'Baskets',
      image: '/images/img14.jpg',
      price: 100,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'basket-2',
      description: 'handmade product',
    },
    {
      //_id: '15',
      name: 'Basket',
      category: 'Baskets',
      image: '/images/img15.jpg',
      price: 90,
      rating: 4.5,
      numReviews: 15,
      countInStock: 0,
      slug: 'basket-3',
      description: 'handmade product',
    },
    {
      // _id: '16',
      name: 'Basket',
      category: 'Baskets',
      image: '/images/img16.jpg',
      price: 100,
      rating: 4.5,
      numReviews: 15,
      countInStock: 6,
      slug: 'basket-4',
      description: 'handmade product',
    },
  ],
};
export default data;
